#ifndef CONSTANTS_H
#define CONSTANTS_H

#define NUM_TILES_X 9
#define NUM_TILES_Y 9

#define PACKET_SIZE 100
#define TERMINATOR 'T'

enum { PLAY=1, LEADERBOARD, QUIT, LOGIN, LOSE, WIN, REVEAL_TILE, FLAG_TILE};

#endif